=== nzbgetcom/nzbget-extensions/json-schema/master-manifest.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://nzbget.com/master-manifest.schema.json",
    "title": "Master list of extensions manifest",
    "description": "NZBGet master list of extension manifest schema",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "name": {
                "description": "The extension name",
                "type": "string"
            },
            "homepage": {
                "description": "Link to the extension homepage",
                "type": "string"
            },
            "displayName": {
                "description": "The name that will be displayed in the web interface",
                "type": "string"
            },
            "version": {
                "description": "Extension version",
                "type": "string"
            },
            "nzbgetMinVersion": {
                "description": "NZBGet minimum required version",
                "type": "string"
            },
            "author": {
                "description": "Author's name",
                "type": "string"
            },
            "license": {
                "description": "Extension license",
                "type": "string"
            },
            "about": {
                "description": "Brief description of the extension",
                "type": "string"
            },
            "url": {
                "description": "URL of extension archive",
                "type": "string"
            }
        },
        "minItems": 0,
        "required": [
            "name",
            "homepage",
            "displayName",
            "version",
            "nzbgetMinVersion",
            "author",
            "license",
            "about",
            "url"
        ]
    }
}

=== nzbgetcom/nzbget-extensions/extensions.json
[
    {
        "name": "VideoSort",
        "homepage": "https://github.com/nzbgetcom/Extension-VideoSort",
        "displayName": "Video Sort",
        "version": "10.7",
        "nzbgetMinVersion": "23.0",
        "author": "Andrey Prygunkov",
        "license": "GNU",
        "about": "Sorts movies and tv shows.",
        "url": "https://github.com/nzbgetcom/Extension-VideoSort/releases/download/v10.7/videosort-10.7-dist.zip"
    },
    {
        "name": "FakeDetector",
        "homepage": "https://github.com/nzbgetcom/Extension-FakeDetector",
        "displayName": "FakeDetector",
        "version": "3.3",
        "nzbgetMinVersion": "23.0",
        "author": "Andrey Prygunkov",
        "license": "GNU",
        "about": "Detects nzbs with fake media files.",
        "url": "https://github.com/nzbgetcom/Extension-FakeDetector/releases/download/v3.3/fakedetector-3.3-dist.zip"
    },
    {
        "name": "FailureLink",
        "homepage": "https://github.com/nzbgetcom/Extension-FailureLink",
        "displayName": "FailureLink",
        "version": "3.2",
        "nzbgetMinVersion": "23.0",
        "author": "Andrey Prygunkov",
        "license": "GNU",
        "about": "Checks videos to determine if they are corrupt. Inform indexer site about failed or corrupt download and request a replacement nzb.",
        "url": "https://github.com/nzbgetcom/Extension-FailureLink/releases/download/v3.2/failurelink-3.2-dist.zip"
    },
    {
        "name": "EMail",
        "homepage": "https://github.com/nzbgetcom/Extension-EMail",
        "displayName": "EMail",
        "version": "2.1",
        "nzbgetMinVersion": "23.0",
        "author": "Andrey Prygunkov",
        "license": "GNU",
        "about": "Sends E-Mail notification.",
        "url": "https://github.com/nzbgetcom/Extension-EMail/releases/download/v2.1/email-2.1-dist.zip"
    },
    {
        "name": "Logger",
        "homepage": "https://github.com/nzbgetcom/Extension-Logger",
        "displayName": "Logger",
        "version": "2.0.0",
        "nzbgetMinVersion": "23.0",
        "author": "Andrey Prygunkov",
        "license": "GNU",
        "about": "Saves nzb log into a file.",
        "url": "https://github.com/nzbgetcom/Extension-Logger/releases/download/v2.0/logger-2.0-dist.zip"
    },
    {
        "name": "ExtendedUnpacker",
        "homepage": "https://github.com/nzbgetcom/Extension-ExtendedUnpacker",
        "displayName": "ExtendedUnpacker",
        "version": "1.2",
        "nzbgetMinVersion": "23.0",
        "author": "piejanssens,thorli",
        "license": "GNU",
        "about": "Unpacks nested zip and rar archives.",
        "url": "https://github.com/nzbgetcom/Extension-ExtendedUnpacker/releases/download/v1.2/extendedunpacker-1.2-dist.zip"
    },
    {
        "name": "PasswordDetector",
        "homepage": "https://github.com/nzbgetcom/Extension-PasswordDetector",
        "displayName": "PasswordDetector",
        "version": "3.1",
        "nzbgetMinVersion": "23.0",
        "author": "JVM",
        "license": "GNU",
        "about": "Detects nzbs with password protected .rar archive.",
        "url": "https://github.com/nzbgetcom/Extension-PasswordDetector/releases/download/v3.1/passworddetector-3.1-dist.zip"
    },
    {
        "name": "EasySort",
        "homepage": "https://github.com/nzbgetcom/Extension-EasySort",
        "displayName": "Easy Sort",
        "version": "3.2",
        "nzbgetMinVersion": "23.0",
        "author": "Andrey Prygunkov",
        "license": "GPLv3",
        "about": "Moves files after download into other locations.",
        "url": "https://github.com/nzbgetcom/Extension-EasySort/releases/download/v3.2/easysort-3.2-dist.zip"
    },
    {
        "name": "NotifyPlex",
        "homepage": "https://github.com/nzbgetcom/Extension-NotifyPlex",
        "displayName": "Notify Plex",
        "version": "4.0",
        "nzbgetMinVersion": "23.0",
        "author": "mannibis",
        "license": "GNU",
        "about": "Post-Processing extension to Update Plex Library.",
        "url": "https://github.com/nzbgetcom/Extension-NotifyPlex/releases/download/v4.0/notifyplex-4.0-dist.zip"
    },
    {
        "name": "NotifySickChill",
        "homepage": "https://github.com/nzbgetcom/Extension-NotifySickChill",
        "displayName": "Notify SickChill",
        "version": "1.1",
        "nzbgetMinVersion": "23.0",
        "author": "Denis",
        "license": "GNU",
        "about": "Post-Processing extension to trigger SickChill after downloads.",
        "url": "https://github.com/nzbgetcom/Extension-NotifySickChill/releases/download/v1.1/notifysickchill-1.1-dist.zip"
    },
    {
        "name": "Completion",
        "homepage": "https://github.com/nzbgetcom/Extension-Completion",
        "displayName": "Completion",
        "version": "3.4",
        "nzbgetMinVersion": "23.0",
        "author": "kloaknet",
        "license": "GPLv3",
        "about": "Verifies that enough articles are available before starting the download.",
        "url": "https://github.com/nzbgetcom/Extension-Completion/releases/download/v3.4/completion-3.4-dist.zip"
    },
    {
        "name": "SpeedControl",
        "homepage": "https://github.com/nzbgetcom/Extension-SpeedControl",
        "displayName": "Speed Control",
        "version": "3.0",
        "nzbgetMinVersion": "24.0",
        "author": "Andrey Prygunkov",
        "license": "GPLv3",
        "about": "Sets speed limit based on category.",
        "url": "https://github.com/nzbgetcom/Extension-SpeedControl/releases/download/v3.0/speedcontrol-3.0-dist.zip"
    },
    {
        "name": "NotifyEmbyJellyfin",
        "homepage": "https://github.com/nzbgetcom/Extension-NotifyEmbyJellyfin",
        "displayName": "Notify Emby/Jellyfin",
        "version": "1.1",
        "nzbgetMinVersion": "23.0",
        "author": "Denis",
        "license": "GNU",
        "about": "Post-Processing extension to trigger Emby/Jellyfin after downloads",
        "url": "https://github.com/nzbgetcom/Extension-NotifyEmbyJellyfin/releases/download/v1.1/notifyembyjellyfin-1.1-dist.zip"
    },
    {
        "name": "RemoveSamples",
        "homepage": "https://github.com/nzbgetcom/Extension-RemoveSamples",
        "displayName": "Remove Samples",
        "version": "1.1.1",
        "nzbgetMinVersion": "23.0",
        "author": "Anunnaki-Astronaut",
        "license": "GPL-2.0-only",
        "about": "Detects and removes sample files/folders; includes an optional Test Mode and Quarantine.",
        "url": "https://github.com/nzbgetcom/Extension-RemoveSamples/releases/download/v1.1.1/removesamples-1.1.1-dist.zip"
    }
]
